# Generated by Django 5.2.7 on 2025-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='spice_level',
            field=models.PositiveBigIntegerField(),
        ),
    ]
