# Generated by Django 5.2.7 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_recipe_spice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hr', 'Hours'), ('day', 'Days'), ('wk', 'Weeks'), ('mo', 'Months')], default='min', max_length=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hr', 'Hours'), ('day', 'Days'), ('wk', 'Weeks'), ('mo', 'Months')], default='min', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(),
        ),
    ]
